# Generated by Django 5.0.3 on 2024-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('short_description', models.TextField(null=True)),
                ('full_description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
