# Generated by Django 5.0.3 on 2024-04-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full_description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
