# Generated by Django 5.0.3 on 2024-04-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='telegram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
