# Generated by Django 5.0.3 on 2024-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutme_instagram_aboutme_telegram_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='full_description',
            field=models.TextField(null=True),
        ),
    ]
